# Generated by Django 4.0.6 on 2022-09-11 10:53

import ckeditor_uploader.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audionews',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.AddField(
            model_name='audionews',
            name='audio_caption',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='audionews',
            name='audio_image',
            field=models.ImageField(blank=True, upload_to='post/audio/image'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='audionews',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='audionews',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='post/audio/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, upload_to='news'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
